# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.6.0-1-g6a5215b
_src_path: gh:epics-containers/services-template-compose
description: t01 IOC Instances and Services
services: t01
