# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: REPLACE WITH DESCRIPTION

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: &PORT DET.DET
    P: &P BL01T-EA-CAM-01
    R: ":DET:"

  - type: ADCore.NDStdArrays
    PORT: DET.ARR
    # use the alias for the same P as the simDetector
    P: *P
    R: ":ARR:"
    NDARRAY_PORT: *PORT
    TYPE: Int8
    FTVL: CHAR
    NELEMENTS: 1048576

  - type: ADCore.NDProcess
    PORT: DET.PROC
    P: BL01T-EA-CAM-01
    R: ":PROC:"
    NDARRAY_PORT: DET.DET
